package com.evs.init.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * User entity represents a user in the voting system.
 * This entity is mapped to the 'users' table in the database.
 * Uses JPA annotations for ORM mapping.
 */
@Entity // Marks this class as a JPA entity, meaning it will be mapped to a database table
@Table(name = "users") // Specifies the table name in the database
@Data // Lombok annotation to generate getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor
@AllArgsConstructor // Lombok annotation to generate a constructor with all fields
public class User {

    /**
     * Primary key for the User entity.
     * Auto-generated by the database.
     */
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID should be auto-generated, typically using database auto-increment
    private Long id;

    /**
     * Unique username for the user.
     * Must be unique across all users.
     */
    @Column(unique = true, nullable = false) // Maps to a database column, unique and not null
    private String username;

    /**
     * Password for the user.
     * Should be encrypted before storing.
     */
    @Column(nullable = false) // Maps to a database column, not null
    private String password;

    /**
     * Email address of the user.
     * Must be unique.
     */
    @Column(unique = true, nullable = false) // Unique and not null
    private String email;

    /**
     * Role of the user in the system.
     * Can be USER, CANDIDATE, VOTER, etc.
     */
    @Enumerated(EnumType.STRING) // Specifies that the enum should be stored as a string in the database
    @Column(nullable = false) // Not null
    private Role role;

    /**
     * Flag to indicate if the user account is enabled.
     * Used for account activation/deactivation.
     */
    @Column(nullable = false) // Not null
    private Boolean enabled = true; // Default value

    /**
     * Enum for user roles.
     */
    public enum Role {
        USER, CANDIDATE, VOTER
    }
}